common:
  dirty_label: камера грязная
  clean_label: камера чистая

classification:
  weights: models/best_cls.pt
  imgsz: 640

segmentation:
  weights: models/best_segm.pt
  imgsz: 224
  bin_thresh: 0.4