common:
  dirty_label: камера грязная
  clean_label: камера чистая

classification:
  weights: submit/classifier.pt
  imgsz: 640

segmentation:
  weights: submit/segmentation.pt
  imgsz: 224
  bin_thresh: 0.4